baseurl: https://rdgrossman.netlify.app
languageCode: en
title: Ryan Grossman
theme: hyde-hyde
params:
  author: Ryan Grossman
  authorimage: ryan.png
  copyright: htr3n
  dateformat: Jan 2, 2006
  highlightjs: yes
  highlightjsstyle: github
  license: CC BY-SA 4.0
  licenseURL: https://creativecommons.org/licenses/by-sa/4.0
  showBuiltWith: yes
  since: 2021
  social:
    email: your-email@example.com
    github: <username>
    instagram: <username>
    linkedin: <username>
    stackoverflow: <username>
    twitter: <username>
    xing: <username>
  title: Title
menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 100
    - identifier: portfolio
      name: Portfolio
      url: /portfolio/
      weight: 200
    - identifier: about
      name: About
      url: /about/
      weight: 300
